import { Room, Client } from "colyseus";
import { GameState } from "./schema/GameState";
import { createLogger } from "../lib/logger";
import { createReqId } from "../lib/logger";
import {
    SetRoleSchema, SetRoleMessage,
    SubmitActionSchema, SubmitActionMessage,
    StartGameSchema, StartGameMessage,
    AdvanceRoundSchema, AdvanceRoundMessage
} from "../../shared/messages";

import { GameController } from "../services/GameController";
import { StateManager } from "./adapters/stateManager";
import { schemaToCore, coreToSchema, schemaPlayerToCore, corePlayerToSchema } from "./adapters/stateAdapter";
import { GamePhase } from "../../types/core";

export class GameRoom extends Room<GameState> {
    maxClients = 6;
    private logger!: ReturnType<typeof createLogger>;
    private rid!: string;
    private gameController: GameController;
    private stateManager!: StateManager;

    constructor() {
        super();
        this.gameController = new GameController();
    }

    // Helper for Zod-validated messages
    private onMessageZod<T>(type: string, schema: any, callback: (client: Client, data: T) => void) {
        this.onMessage(type, (client, message) => {
            const result = schema.safeParse(message);
            if (!result.success) {
                this.logger.warn(this.rid, `Invalid message ${type}`, { error: result.error, clientId: client.sessionId });
                client.send("error", { message: "Invalid message format" });
                return;
            }
            callback(client, result.data);
        });
    }

    onCreate(options: any) {
        this.rid = createReqId('room');
        this.setState(new GameState());

        // Initialize StateManager with Democratic Legitimacy as default metric
        this.stateManager = new StateManager({
            initialCoreMetricName: "Democratic Legitimacy",
            initialCoreMetricValue: 75
        });

        // Project Core state to Schema (initial sync)
        const coreState = this.stateManager.getCoreState();
        coreToSchema(coreState, this.state);

        // Set room code (will be generated by room code service later)
        this.state.roomCode = ""; // Will be set by room code generator later

        // Create logger with roomId context
        this.logger = createLogger({ roomId: this.roomId });

        // Extract traceId from options if provided by client
        const traceId = options.traceId || 'no-trace';
        this.logger.info(this.rid, "Room created", { traceId, options });

        // --- Message Handlers ---

        this.onMessage("ping", (client, message) => {
            this.logger.info(this.rid, "Ping received", { clientId: client.sessionId, message });
            client.send("pong", { message: "pong" });
        });

        // Set Role Handler
        console.log(`[${this.rid}] Registering set_role handler`);
        this.onMessageZod("set_role", SetRoleSchema, (client, data: SetRoleMessage) => {
            const player = this.state.players.get(client.sessionId);
            if (player) {
                player.role = data.role;
                if (data.name) player.name = data.name;
                this.logger.info(this.rid, "Role set", { playerId: client.sessionId, role: data.role });
            }
        });

        // Submit Action Handler
        this.onMessageZod("submit_action", SubmitActionSchema, (client, data: SubmitActionMessage) => {
            const player = this.state.players.get(client.sessionId);
            if (player && !player.hasSubmitted) {
                // Check action points (simple check for now)
                if (player.actionPoints >= data.cost) {
                    player.actionPoints -= data.cost;
                    player.hasSubmitted = true;
                    this.logger.info(this.rid, "Action submitted", { playerId: client.sessionId, action: data.actionId });

                    // Check if all submitted (optional auto-advance logic could go here)
                    if (this.state.allSubmitted()) {
                        this.broadcast("all_submitted");
                    }
                } else {
                    client.send("error", { message: "Not enough action points" });
                }
            }
        });

        // Start Game Handler
        this.onMessageZod("start_game", StartGameSchema, (client, data: StartGameMessage) => {
            // TODO: Add host check
            if (this.state.phase === "lobby") {
                this.state.phase = "action";
                this.state.round = 1;
                this.state.resetSubmissions();
                this.broadcast("game_started");
                this.logger.info(this.rid, "Game started", { initiatedBy: client.sessionId });
            }
        });

        // Advance Round Handler
        this.onMessageZod("advance_round", AdvanceRoundSchema, async (client, data: AdvanceRoundMessage) => {
            console.log(`[${this.rid}] advance_round message received`);
            // TODO: Add host check
            if (this.state.phase === "action" || this.state.phase === "consequence") {
                console.log(`[${this.rid}] Phase is valid: ${this.state.phase}`);

                this.logger.info(this.rid, "Advancing round via GameController + StateManager...");

                try {
                    // 1. Enrich: Get full Core state from StateManager
                    const coreState = this.stateManager.getCoreState();
                    const corePlayers = this.stateManager.getCorePlayers();

                    this.logger.info(this.rid, "Core state retrieved", {
                        phase: coreState.phase,
                        round: coreState.round,
                        playerCount: corePlayers.length
                    });

                    // 2. Call GameController with full Core state
                    const { newState, newPlayers } = await this.gameController.advanceRound(
                        this.roomId,
                        coreState,
                        corePlayers,
                        [] // humanAvailableOptions - empty for now
                    );

                    // 3. Persist updated Core state in StateManager
                    this.stateManager.setCoreState(newState);
                    this.stateManager.setCorePlayers(newPlayers);

                    // 4. Project: Core → Schema (broadcast to clients)
                    coreToSchema(newState, this.state);

                    // Also update players
                    for (const corePlayer of newPlayers) {
                        const schemaPlayer = this.state.players.get(corePlayer.id);
                        if (schemaPlayer) {
                            corePlayerToSchema(corePlayer, schemaPlayer);
                        }
                    }

                    this.broadcast("new_round", { round: this.state.round });
                    this.logger.info(this.rid, "Round advanced successfully", { round: newState.round });

                } catch (error) {
                    this.logger.error(this.rid, "Failed to advance round", { error });
                    client.send("error", { message: "Failed to advance round" });
                }
            }
        });
    }

    onJoin(client: Client, options: any) {
        // Store traceId in client for logging correlation
        (client as any).traceId = options.traceId || createReqId('trace');

        this.logger.info(this.rid, "Client joined", {
            sessionId: client.sessionId,
            traceId: (client as any).traceId,
            name: options.name,
            role: options.role,
        });

        const playerName = options.name || `Guest-${client.sessionId.slice(0, 4)}`;
        const roleName = options.role || "";

        // Create player in Schema (for network sync)
        this.state.createPlayer(client.sessionId, {
            name: playerName,
            role: roleName,
            isHuman: options.isHuman ?? true,
        });

        // Also create player in StateManager (for Core state)
        // TODO: This needs full role object with objectives/resources/constraints
        // For now, we create a minimal role structure
        this.stateManager.addPlayer({
            id: client.sessionId,
            role: {
                name: roleName,
                publicObjective: "",
                hiddenObjective: "",
                resources: [],
                constraints: []
            },
            isHuman: options.isHuman ?? true,
            actionPoints: 3,
            actions: [],
            hasSubmittedActions: false,
            hiddenScore: 0
        });
    }

    onLeave(client: Client, consented: boolean) {
        this.logger.info(this.rid, "Client left", {
            sessionId: client.sessionId,
            traceId: (client as any).traceId,
            consented,
        });

        // Remove from Schema (network sync)
        this.state.removePlayer(client.sessionId);

        // Remove from StateManager (Core state)
        this.stateManager.removePlayer(client.sessionId);
    }

    onDispose() {
        this.logger.info(this.rid, "Room disposing", {
            roomId: this.roomId,
        });
    }
}
