/** Backend-safe core types (no React dependencies) */
import type { Policy } from './policy.js';

// Re-export policy types and utilities from policy.ts (enum-free module for cross-package compatibility)
export type {
  PolicyDimensionConfig,
  PolicyStance,
  Policy
} from './policy.js';

/**
 * CP5: Intent Data Structure
 * Centralized intent types - single source of truth
 */

/**
 * Predicted effects of an intent on resources and core metric
 */
export interface IntentDeltas {
  targetResources?: Partial<Resources>;  // Predicted changes to target's M/I/N
  sourceResources?: Partial<Resources>;  // Predicted changes to source's M/I/N
  coreMetric?: number;                   // Predicted change to global score [-100, +100]
}

/**
 * Intent represents a player action with predicted effects
 * Generated by LLM based on player policy and game state
 */
export interface Intent {
  id: string;                           // Unique identifier: `${playerId}-intent-${index}`
  source: string;                       // Player ID who can execute this intent
  target: string;                       // Target entity (GLOBAL, ENVIRONMENT, stakeholder name)
  cost: number;                         // Action points required (1-3)
  deltas: IntentDeltas;                 // Predicted effects
  title: string;                        // Human-readable action name
  description: string;                  // Detailed description
  risk: 'low' | 'medium' | 'high';      // Risk assessment
}

export {
  PRIVACY,
  SECURITY,
  TRANSPARENCY,
  ACCOUNTABILITY,
  INNOVATION,
  REGULATION,
  ALL_POLICY_DIMENSIONS,
  POLICY_DIMENSION_MAP,
  createDefaultPolicy,
  updatePolicyStance,
  getPolicyStance,
  validatePolicy
} from './policy.js';

export enum RoleName {
  ELECTION_COMMISSIONER = "Election Commissioner",
  TECH_CEO = "Tech CEO",
  JOURNALIST = "Journalist",
  FEDERAL_REGULATOR = "Federal Regulator",
  CAMPAIGN_MANAGER = "Campaign Manager",
  CYBERSECURITY_EXPERT = "Cybersecurity Expert",
}

export interface RoleDataCore {
  name: string;
  publicObjective: string;
  hiddenObjective: string;
  resources: string[];
  constraints: string[];
}

export interface CoreMetric {
  name: string;
  description: string;
  value: number;
}

/**
 * Player resources (CP3)
 * All values in range [0, 100]
 */
export interface Resources {
  material: number;      // M: Money, compute, physical assets
  institutional: number; // I: Authority, legal power, access
  narrative: number;     // N: Public trust, media influence
}

export interface StakeholderData {
  name: string;
  icon: string;
  publicObjective: string;
  hiddenObjective: string;
  resources?: string[]; // Role abilities/descriptions
  constraints?: string[];
  initialResources?: Resources; // Starting M/I/N values (CP3)
}

export interface GameSetup {
  scenarioTitle: string;
  scenarioDescription: string;
  coreMetric: CoreMetric;
  stakeholders: StakeholderData[];
  // Phase 1: Add optional game configuration (from canonical schema)
  maxRounds?: number | null;
  maxAIPlayers?: number | null;
}

export interface ActionOption {
  title: string;
  description: string;
  cost: number;
}

export interface Player {
  id: string;
  role: RoleDataCore;
  isHuman: boolean;
  resources: Resources;
  hiddenScore: number;
  actionPoints: number;
  actions: ActionOption[];
  hasSubmittedActions: boolean;
  policy?: Policy;         // Player's strategic policy (CP4)
}

export enum GamePhase {
  LOBBY = 'lobby',
  STARTING = 'starting',
  ACTION = 'action',
  CONSEQUENCE = 'consequence',
  END = 'end',
}

export interface GameEvent { headline: string; detail: string; }

export interface PlayerRoundActions {
  roleName: string;
  actions: ActionOption[];
  availableOptions: ActionOption[];
  isHuman: boolean;
}

export interface HiddenScoreUpdate { update: number; justification: string; }
export interface AIHiddenScoreUpdate { roleName: string; update: number; justification: string; }

export interface OutcomeTimelineItem { title: string; description: string; impact: string; }

export interface GameLogEntry {
  round: number;
  roundSummary: string;
  outcomeTimeline: OutcomeTimelineItem[];
  counterfactualNote: string;
  event: GameEvent | null;
  playerActions: PlayerRoundActions[];
  publicScoreChange: number;
  publicScoreAfter: number;
  hiddenScoreChanges: Record<string, HiddenScoreUpdate>;
  geminiCalls: number;
}

export interface GameState {
  phase: GamePhase;
  round: number;
  coreMetric: CoreMetric;
  eventLog: GameLogEntry[];
  currentEvent: GameEvent | null;
  hostId?: string; // sessionId of host; projection from Schema
}

export interface AIConsequenceResponse {
  roundSummary: string;
  outcomeTimeline: OutcomeTimelineItem[];
  counterfactualNote: string;
  publicScoreUpdate: number;
  hiddenScoreUpdates: AIHiddenScoreUpdate[];
  nextEvent: GameEvent;
}

export interface AIActionOptionsResponse { options: ActionOption[]; }
export interface AICounterfactualResponse { publicScoreUpdate: number; }
export interface AIPlayerActionsResponse { actions: ActionOption[]; }

export interface AITurnResponse {
  options: ActionOption[];
  chosenActions: ActionOption[];
  reasoning: string;
}

// Causal reference types
export type CausalRefType = 'event' | 'action' | 'exogenous';

export interface CausalReference {
  type: CausalRefType; // what is being cited
  ref: string;         // event id or action descriptor
  rationale: string;   // short explanation of the causal link
}

// Debrief types
export interface AIDebriefEvent { round: number; title: string; description: string; impact: string; actor: string | null; causes?: CausalReference[] }
export interface AIDebriefAction { round: number; title: string; impact: string; rationale: string | null }
export interface AIDebriefResponse {
  summary: string;
  keyEvents: AIDebriefEvent[];
  userActions: AIDebriefAction[];
}
