#!/bin/bash

# Simulacra - Local Database Setup Script
# This script helps set up PostgreSQL locally for development

set -e  # Exit on error

echo "🎮 Simulacra - Local Database Setup"
echo "========================================="
echo ""

# Colors for output
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
RED='\033[0;31m'
NC='\033[0m' # No Color

# Check if PostgreSQL is installed
echo "Checking for PostgreSQL..."
if ! command -v psql &> /dev/null; then
    echo -e "${RED}❌ PostgreSQL is not installed${NC}"
    echo ""
    echo "Please install PostgreSQL:"
    echo "  macOS:   brew install postgresql@16"
    echo "  Ubuntu:  sudo apt-get install postgresql postgresql-contrib"
    echo "  Arch:    sudo pacman -S postgresql"
    echo ""
    exit 1
fi

echo -e "${GREEN}✓ PostgreSQL found${NC}"
PG_VERSION=$(psql --version | awk '{print $3}')
echo "  Version: $PG_VERSION"
echo ""

# Check if PostgreSQL service is running
echo "Checking PostgreSQL service..."
if ! pg_isready -q; then
    echo -e "${YELLOW}⚠ PostgreSQL service is not running${NC}"
    echo ""
    echo "Starting PostgreSQL service..."

    start_ok=false
    # Try different commands based on OS
    set +e

    if [[ "$OSTYPE" == "darwin"* ]]; then
        # macOS
        if command -v brew &> /dev/null; then
            brew services start postgresql@16 || brew services start postgresql
            start_ok=$?
        fi
    elif [[ "$OSTYPE" == "linux-gnu"* ]]; then
        # Linux
        if command -v systemctl &> /dev/null; then
            if sudo -n true 2>/dev/null; then
                sudo systemctl start postgresql
                start_ok=$?
            else
                systemctl --user start postgresql 2>/dev/null
                start_ok=$?
            fi
        fi

        if [[ $start_ok != 0 ]] && command -v service &> /dev/null; then
            if sudo -n true 2>/dev/null; then
                sudo service postgresql start
                start_ok=$?
            else
                service postgresql start 2>/dev/null
                start_ok=$?
            fi
        fi
    fi
    set -e

    sleep 2

    if ! pg_isready -q; then
        echo -e "${RED}❌ Failed to start PostgreSQL${NC}"
        echo "Please start PostgreSQL manually and run this script again."
        echo "Suggested commands:"
        echo "  macOS:   brew services start postgresql@16"
        echo "  Linux:   sudo systemctl start postgresql"
        exit 1
    fi
fi

echo -e "${GREEN}✓ PostgreSQL service is running${NC}"
echo ""

# Database configuration
DB_NAME="simulacra_local"
DB_USER="${USER}"
DB_PORT="5432"

echo "Database Configuration:"
echo "  Name: $DB_NAME"
echo "  User: $DB_USER"
echo "  Port: $DB_PORT"
echo ""

# Check if database already exists
if psql -lqt | cut -d \| -f 1 | grep -qw "$DB_NAME"; then
    echo -e "${YELLOW}⚠ Database '$DB_NAME' already exists${NC}"
    read -p "Do you want to drop and recreate it? (y/N) " -n 1 -r
    echo
    if [[ $REPLY =~ ^[Yy]$ ]]; then
        echo "Dropping existing database..."
        dropdb "$DB_NAME" || true
        echo "Creating new database..."
        createdb "$DB_NAME"
        echo -e "${GREEN}✓ Database recreated${NC}"
    else
        echo "Using existing database"
    fi
else
    echo "Creating database '$DB_NAME'..."
    createdb "$DB_NAME"
    echo -e "${GREEN}✓ Database created${NC}"
fi

echo ""

# Update .env file
ENV_FILE=".env"
DATABASE_URL="postgresql://$DB_USER@localhost:$DB_PORT/$DB_NAME?schema=public"

echo "Updating .env file..."

if [ -f "$ENV_FILE" ]; then
    # Check if DATABASE_URL exists in .env
    if grep -q "^DATABASE_URL=" "$ENV_FILE"; then
        # Update existing DATABASE_URL
        if [[ "$OSTYPE" == "darwin"* ]]; then
            # macOS (BSD sed)
            sed -i '' "s|^DATABASE_URL=.*|DATABASE_URL=\"$DATABASE_URL\"|" "$ENV_FILE"
        else
            # Linux (GNU sed)
            sed -i "s|^DATABASE_URL=.*|DATABASE_URL=\"$DATABASE_URL\"|" "$ENV_FILE"
        fi
        echo -e "${GREEN}✓ Updated DATABASE_URL in .env${NC}"
    else
        # Add DATABASE_URL
        echo "" >> "$ENV_FILE"
        echo "# Database (auto-generated by setup-local-db.sh)" >> "$ENV_FILE"
        echo "DATABASE_URL=\"$DATABASE_URL\"" >> "$ENV_FILE"
        echo -e "${GREEN}✓ Added DATABASE_URL to .env${NC}"
    fi
else
    echo -e "${RED}❌ .env file not found${NC}"
    echo "Creating .env file..."
    cat > "$ENV_FILE" << EOF
# Database (auto-generated by setup-local-db.sh)
DATABASE_URL="$DATABASE_URL"

# LLM Configuration (fill these in manually)
VITE_LITELLM_API_KEY="your-api-key-here"
VITE_LLM_MODEL="gpt-4o-mini"
EOF
    echo -e "${GREEN}✓ Created .env file${NC}"
    echo -e "${YELLOW}⚠ Don't forget to add your VITE_LITELLM_API_KEY!${NC}"
fi

echo ""

# Run Prisma migrations
echo "Running Prisma migrations..."
npx prisma migrate dev --name init

echo ""
echo -e "${GREEN}✓ Database setup complete!${NC}"
echo ""
echo "Next steps:"
echo "  1. Run 'npm run dev' to start the development server"
echo "  2. Run 'npx prisma studio' to view your database in a GUI"
echo "  3. Test the feedback API with: ./scripts/test-feedback-api.sh"
echo ""
echo "Database URL: $DATABASE_URL"
